const unitsStyle = {
  singular: {
    narrow: {
      years: "y",
      quarters: "q",
      months: "m",
      weeks: "w",
      days: "d",
      hours: "h",
      minutes: "m",
      seconds: "s",
      milliseconds: "ms",
    },
    short: {
      years: "yr",
      quarters: "qtr",
      months: "mon",
      weeks: "wk",
      days: "dy",
      hours: "hr",
      minutes: "min",
      seconds: "sec",
      milliseconds: "ms",
    },
    long: {
      years: "year",
      quarters: "quarter",
      months: "month",
      weeks: "week",
      days: "day",
      hours: "hour",
      minutes: "minute",
      seconds: "second",
      milliseconds: "millisecond",
    },
  },

  plural: {
    narrow: {
      years: "y",
      quarters: "q",
      months: "m",
      weeks: "w",
      days: "d",
      hours: "h",
      minutes: "m",
      seconds: "s",
      milliseconds: "ms",
    },
    short: {
      years: "yrs",
      quarters: "qtrs",
      months: "mons",
      weeks: "wks",
      days: "dys",
      hours: "hrs",
      minutes: "mins",
      seconds: "secs",
      milliseconds: "mss",
    },
    long: {
      years: "years",
      quarters: "quarters",
      months: "months",
      weeks: "weeks",
      days: "days",
      hours: "hours",
      minutes: "minutes",
      seconds: "seconds",
      milliseconds: "milliseconds",
    },
  },
};

module.exports = unitsStyle;
